### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by hugosenari** [TinHead/nixos-firehol#1]
There is a nice tool called [NMD](https://gitlab.com/rycee/nmd)

It may help create documentation for your module.

Example:

https://hugosenari.github.io/friendly-modules/nixos-firehol.html

**Comment by TinHead** [comment]
Nice! I wasn't aware of it I'll have a look.

**Comment by TinHead** [comment]
> 

Well I had a quick look it isn't obvious at all for me how to use it, would you be able to point me to the right direction?

**Comment by hugosenari** [comment]
I think the best example is [author own configs](https://gitlab.com/rycee/nur-expressions/-/blob/master/doc/default.nix#L47), and he made it to [home-manager](https://github.com/nix-community/home-manager/blob/master/flake.nix#L94)

Another option would be, add [devshell](https://github.com/numtide/devshell) and [my modules](https://cruel-intentions.github.io/devshell-files/document.html) as your dependency.

Or clone [my example repository](https://github.com/hugosenari/friendly-modules) and [update the hash](https://github.com/hugosenari/friendly-modules/blob/master/nixos-firehol.nix), run `nix develop` and it generates the /gh-pages/src/nixos-firehol.md

<sub>Think it is in order of solution elegance ;-)</sub>

**Comment by TinHead** [comment]
Shamelessly stolen your stuff (hope that's ok :) ), hacked it to work for this and put it inside /docs and got the output there https://tinhead.github.io/nixos-firehol/nixos-firehol.html 
For some reason jekil does not create an index.html out of it ... I'll look some more into it .

**Comment by hugosenari** [comment]
Someone sent-me this right now ;-)

![shot-2023-02-16_14-56-25](https://user-images.githubusercontent.com/863299/219448601-3c7592af-e718-4b51-8086-ad7465542be3.jpg)

Closing as DONE

**Comment by hugosenari** [comment]
> Shamelessly stolen your stuff (hope that's ok :) )

To honest, WTFPL is my point of view about this subject at all, also "[Every thing is a Remix](https://www.everythingisaremix.info/about)", but sometimes we have to be formal.

https://en.wikipedia.org/wiki/Wikipedia:Example_requests_for_permission#Bowen_Panoramic_Permission

---
Dear Sir or Madam: I hereby assert that I am the creator and/or sole owner of the exclusive copyright of WORK “[Friendly Modules](https://github.com/hugosenari/friendly-modules/commits/master)”

I agree to publish that work under the free license own work, all rights, released (Multi-license MIT, Unlicense, WTFPL all versions).

I acknowledge that I grant anyone the right to use the work in a commercial product and to modify it according to their needs, provided that they abide by the terms of the license and any other applicable laws.

I am aware that I always retain copyright of my work, and retain the right to be attributed in accordance with the license chosen. Modifications others make to the work will not be attributed to me.

I acknowledge that I cannot withdraw this agreement, and that the content may or may not be kept permanently on a distributed  or centralized version control system project.

This work points to other people work, I don't have copyright permisson about other people work, please confirm with them in case you're using code path linked to theirs project. It the reason why the project doesn't have a license.

Hugo Sena Ribeiro
São Paulo, SP, Brasil, 2023/02/16

**Comment by TinHead** [comment]
OMG Hugo 😂 You are totally awesome!
